CSE/urls.py

from django.urls import path
from CSE import views
from CSE.views import StuList, Forms, StudentDetail, StudentUpdate, StudentDelete

app_name = 'CSE'

urlpatterns = [
    path('index', views.index, name='home'),
    path('index', views.index, name='index'),
    path('products', views.products, name='products'),
    path('service', views.service, name='service'),
    path('contacts', views.contacts, name='contacts'),
    path('basic', views.basic, name='basic'),

    # CBV
    path('', StuList.as_view(), name='list'),
    path('forms', Forms.as_view(), name='forms'),
    path('<pk>/detail', StudentDetail.as_view(), name='detail'),
    path('<pk>/update', StudentUpdate.as_view(), name='update'),
    path('<pk>/delete', StudentDelete.as_view(), name='delete'),

    # FBV
    path('student', views.student, name='student'),  # Only keep one
    path('form', views.form, name='form'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

    ###GET and POST

    path('nie',views.nie, name = 'nie'),
    path('add', views.add, name = 'add'),
    path('add1', views.add1, name = 'add1'),

    # login, logout, user registration
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),

]

NIE/CSE/urls.py
from django.urls import path
from CSE import views
from CSE.views import StuList,Forms, StudentDetail, StudentUpdate, StudentDelete

app_name='CSE'
urlpatterns = [
 path('index', views.index, name = 'index'),
path('products', views.products, name = 'products'),
path('service', views.service, name = 'service'),
path('contacts', views.contacts, name = 'contacts'),
path('basic', views.basic, name = 'basic'),
path('studentList', views.studentList, name = 'studentList'),  

path('', StuList.as_view(), name = 'list'),
path('forms', Forms.as_view(), name = 'forms'),
path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),


]

NIE/urls.py


from django.contrib import admin
from django.urls import path

from zay import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index',views.index, name='home'),
    path('about',views.about, name='about'),
    path('shop',views.shop, name='shop'),
    path('contact',views.contact, name='contact'),
]

NIE/CSE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=30)
    college_name = models.CharField(max_length=30)
    rollnumber = models.IntegerField()
    def __str__(self):
        return self.name
    

NIE/zay/models.py
from django.db import models

# Create your models here.

NIE/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html', context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')


def basic(request):
    return render(request,'basic.html')

from CSE.models import Student
def studentList(request):
    students = Student.objects.all()
    context = {'students':students}
    return render(request,'studentList.html', context)  
  


from CSE.models import Student
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = Student
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = Student
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = Student
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'

class StudentDelete(DeleteView):
    model = Student
    template_name = 'CBV/delete.html'
    success_url = '/'

NIE/zay/views.py

# Create your views here.
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')
def about(request):
    return render(request, 'about.html')
def shop(request):
    return render(request, 'shop.html')
def contact(request):
    return render(request, 'contact.html')

NIE/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
{% comment %} navbar {% endcomment %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'CSE:index' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:products' %}">Products</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link"href="{% url 'CSE:service' %}">Services</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:contacts' %}">Contacts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:studentList' %}">StudentList</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:list' %}">FBV</a>
          </li>      
      </div>
    </div>
  </nav>
{% block content %}
{% endblock %}
</body>
</html>

NIE/templates/basic1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Contacts</a>
              </li>
              
                      
          </div>
        </div>
      </nav>
<!-- navbar -->
  <!-- button -->
  <button type="button" class="btn btn-primary">Primary</button>
  <button type="button" class="btn btn-secondary">Secondary</button>
  <button type="button" class="btn btn-success">Success</button>
  <button type="button" class="btn btn-danger">Danger</button>
  <button type="button" class="btn btn-warning">Warning</button>
  <button type="button" class="btn btn-info">Info</button>
  <button type="button" class="btn btn-light">Light</button>
  <button type="button" class="btn btn-dark">Dark</button>
  
  <button type="button" class="btn btn-link">Link</button>

<!-- cards -->
 
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<!-- card-body -->
<div class="card">
  <div class="card-body">
    This is some text within a card body.
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

NIE/templates/contacts.html
{% extends 'basic.html' %}

{% block content %}

<h1>This is a contact page</h1>

{% endblock %}

NIE/templates/products.html
{% extends 'basic.html' %}

{% block content %}
<h1>
This is a products page.</h1>

Name: {{name}}<br>
College name : {{c_name}}<br>
Department Name : {{d_name}}<br>
Rollnumber : {{r_number}}<br>
{% endblock %}

NIE/templates/service.html
{% extends 'basic.html' %}

{% block content %}

<h1>This is a service page </h1>

{% endblock %}

NIE/templates/studentList.html
{% include "basic.html" %}

 {% block content %}

 {% for student in students %}
 
 Name:{{student.name}}<br>
 Department: {{student.department}}<br>
 College Name: {{student.college_name}}<br>
 Roll number: {{student.rollnumber}}<br>
 <hr>



 {% endfor %}
 
 {% endblock %}